# Generated by Django 3.1.3 on 2020-11-16 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enderecos', '0001_initial'),
        ('core', '0003_pontoturistico_avaliacoes'),
    ]

    operations = [
        migrations.AddField(
            model_name='pontoturistico',
            name='endereco',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='enderecos.endereco'),
        ),
    ]
