# Generated by Django 3.1.3 on 2020-11-16 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_pontoturistico_endereco'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('idade', models.DecimalField(decimal_places=2, max_digits=3)),
                ('cidade', models.TextField(max_length=100)),
            ],
        ),
    ]
