# Generated by Django 3.1.3 on 2020-11-16 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20201116_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='idade',
            field=models.DecimalField(decimal_places=0, max_digits=3),
        ),
    ]
