# Generated by Django 3.1.3 on 2020-11-16 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20201116_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='id',
            field=models.DecimalField(decimal_places=0, max_digits=2, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='nome',
            field=models.TextField(max_length=50),
        ),
    ]
